---

- hosts: localhost
  name: WebServer Setup
  become: yes
  tasks:
  - name: Installing Apache2 Packages 
    apt: name=apache2 state=present

  - name: Start Apache2 Service
    service: name=apache2 state=started
